name: easy_meal
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0-323.0.dev

dependencies:
  build_runner: ^2.4.15
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  http: ^1.4.0
  intl: ^0.20.2
  sizer: ^3.0.5
  go_router: ^15.1.2
  responsive_sizer: ^3.3.1
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    #- assets/MouadPart/
    # - assets/MouadPart/dejeuner.png
    # - assets/MouadPart/dejeuner.png
  fonts:
    - family: Edu NSW ACT Foundation
      fonts:
        - asset: assets/fonts/EduNSWACTFoundation-Bold.ttf
        - asset: assets/fonts/EduNSWACTFoundation-Medium.ttf
        - asset: assets/fonts/EduNSWACTFoundation-Regular.ttf
        - asset: assets/fonts/EduNSWACTFoundation-SemiBold.ttf
